### ISSUE TITLE
webp installation fails with python2.7

### ISSUE THREAD

**Issue by saikiran6** [anibali/pywebp#1]
I got following error while installing webp in ubuntu 14.04. Please help me.

Running setup.py clean for webp
Failed to build webp
Installing collected packages: webp
  Running setup.py install for webp ... error
running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/webp
    copying webp/__init__.py -> build/lib.linux-x86_64-2.7/webp
    copying webp/webp_build.py -> build/lib.linux-x86_64-2.7/webp
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_webp.c'
    creating build/temp.linux-x86_64-2.7
    building '_webp' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aiengine/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/_webp.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_webp.o
    build/temp.linux-x86_64-2.7/_webp.c:429:29: fatal error: webp/decode.h: No such file or directory
         #include <webp/decode.h>
                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by anibali** [comment]
I haven't tested this library with Python 2, so I'm not sure whether it will work out of the box. However, your current problem is unrelated to the Python version - it seems that you don't have the webp libraries and header files installed. Please download [libwebp 0.6.0](https://github.com/webmproject/libwebp/releases/tag/v0.6.0) and install it with libwebpdemux and libwebpmux enabled. Something like:

```sh
./configure --enable-libwebpmux --enable-libwebpdemux
make
make install
```

**Comment by saikiran6** [comment]
Thanks for your suggestions. I installed libwebp 0.6.0 as per your instructions. Using swig instructions, I also created python support for libwebp. I was able to check the pseudo example as given below

-------------------------------------- BEGIN PSEUDO EXAMPLE
import glob
import sys
sys.path.append(glob.glob('pylocal/lib/python*/site-packages')[0])

from com.google.webp import libwebp
print "libwebp decoder version: %x" % libwebp.WebPGetDecoderVersion()

print "libwebp attributes:"
for attr in dir(libwebp): print attr
-------------------------------------- END PSEUDO EXAMPLE

But how to read an webp image with the current installed setup in python. Can you please suggest me any option.

**Comment by anibali** [comment]
This pywebp library doesn't use SWIG, it uses FFI. If you want to use SWIG bindings, you need to look elsewhere for help.

If you want to use my FFI bindings, install pywebp like you were trying to do originally, then follow my [README examples](https://github.com/anibali/pywebp#usage) or look at [the tests](https://github.com/anibali/pywebp/blob/master/tests/test_webp.py) as a reference.

**Comment by saikiran6** [comment]
Hi, 
I tried doing it as you mentioned. I installed python 3.6. I installed libwebp. pip install webp is also successfully done. 
But Iam getting following error while import web 
ImportError: libwebpdemux.so.2: cannot open shared object file: No such file or directory

I didnt do this step while installing libwebp
Building for MIPS Linux:
------------------------
MIPS Linux toolchain stable available releases can be found at:
https://community.imgtec.com/developers/mips/tools/codescape-mips-sdk/available-releases/

# Add toolchain to PATH
export PATH=$PATH:/path/to/toolchain/bin

# 32-bit build for mips32r5 (p5600)
HOST=mips-mti-linux-gnu
MIPS_CFLAGS="-O3 -mips32r5 -mabi=32 -mtune=p5600 -mmsa -mfp64 \
  -msched-weight -mload-store-pairs -fPIE"
MIPS_LDFLAGS="-mips32r5 -mabi=32 -mmsa -mfp64 -pie"

# 64-bit build for mips64r6 (i6400)
HOST=mips-img-linux-gnu
MIPS_CFLAGS="-O3 -mips64r6 -mabi=64 -mtune=i6400 -mmsa -mfp64 \
  -msched-weight -mload-store-pairs -fPIE"
MIPS_LDFLAGS="-mips64r6 -mabi=64 -mmsa -mfp64 -pie"

./configure --host=${HOST} --build=`config.guess` \
  CC="${HOST}-gcc -EL" \
  CFLAGS="$MIPS_CFLAGS" \
  LDFLAGS="$MIPS_LDFLAGS"
make
make install

No proper instructions given what mips library to install and how to install.

I downloaded below files
CodescapeMIPSSDK-1.4.1.07-linux-x64-installer.run
Codescape.GNU.Tools.Package.2016.05-03.for.MIPS.IMG.Linux.CentOS-5.x86_64.tar.gz
linux-4.13.5.tar.xz

Not able to figure out which one to install. 

Please suggest me how to go ahead with mips installation

Thanks

**Comment by saikiran6** [comment]
Hi, 
Now I am able to import webp in python. But not able to load webp image
Iam getting the following error.. please suggest me

Traceback (most recent call last):
  File "/home/name/workspace/Segmentation_Framework/For_HPC_Split_Folder/Test_libwebpLibrary.py", line 23, in <module>
    img = webp.load_image('27_39.webp', 'RGB')
  File "/home/name/anaconda2/lib/python2.7/site-packages/webp/__init__.py", line 445, in load_image
    arr = webp_data.decode(color_mode=color_mode)
  File "/home/name/anaconda2/lib/python2.7/site-packages/webp/__init__.py", line 83, in decode
    dec_config.read_features(self)
  File "/home/name/anaconda2/lib/python2.7/site-packages/webp/__init__.py", line 231, in read_features
    raise WebPError('failed to read features')
webp.WebPError: failed to read features

**Comment by anibali** [comment]
Can you please post the image loading code and a link to the image you are trying load so that I can try to reproduce the problem myself?

**Comment by anibali** [comment]
Closing due to no response.
