### ISSUE TITLE
0.1.0a12 release doesn't include latest changes

### ISSUE THREAD

**Issue by egonina** [anibali/pywebp#10]
Looks like the latest release (0.1.0a12) doesn't include the latest commit (https://github.com/anibali/pywebp/commit/30df199faa56c6af4795402759eb4ac8efea01ec#diff-2eeaed663bd0d25b7e608891384b7298). Could you please create a new release that includes the latest changes to setup.py? Thanks! 

cc @sguada

**Comment by anibali** [comment]
Released webp-0.1.0a13.

**Comment by egonina** [comment]
Thank you!
