### ISSUE TITLE
Create a non-alpha release

### ISSUE THREAD

**Issue by wearypossum4770** [anibali/pywebp#19]
##### System: 
- No LSB modules are available.
- Distributor ID: Debian
- Description:    Debian GNU/Linux 10 (buster)
- Release: 10
- Codename:  buster

##### Environment:
- pipenv, version 11.9.0
- Python version 3.7.3

### Issue: 
  feat: consider supporting semantic versioning. 
#### Acceptance Criteria:
Developer removes "alpha", "beta", pre/post release from final development cycle release version.
```

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches webp
Tried: 0.1.0a4, 0.1.0a5, 0.1.0a6, 0.1.0a7, 0.1.0a9, 0.1.0a10, 0.1.0a11, 0.1.0a12, 0.1.0a13, 0.1.0a14, 0.1.0a15, 0.1.0a16

```

### Rule: 

1. [Pipenv Recommendations](https://pipenv.pypa.io/en/latest/basics/#general-recommendations-version-control) 

2. [PEP 449 -- Version Identification and Dependency Specification](https://www.python.org/dev/peps/pep-0440/) 

3. [version precedence](https://semver.org/#spec-item-11) 

### Analysis and Conclusion:

As a user I would like to install a package without errors, warnings or bugs. I should be able to use environment manager of choice  without settings additional constraints. The environment manager should be able to create a dependency map (lock file) without additional command line options.

**Comment by anibali** [comment]
I've made a 0.1.0 release, hopefully this helps.
