### ISSUE TITLE
[Installation] Failed building wheel for webp

### ISSUE THREAD

**Issue by junkwhinger** [anibali/pywebp#2]
Hi, thanks for sharing a great project.

I'm having trouble with installing pywebp via "pip install webp".
I get the following error message.

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\junsik.whang\appdata\local\continuum\anaconda3\envs\pytorch\libs /LIBPATH:c:\users\junsik.whang\appdata\local\continuum\anaconda3\envs\pytorch\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" webp.lib webpdemux.lib webpmux.lib /EXPORT:PyInit__webp build\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\_webp.obj /OUT:build\lib.win-amd64-3.6\_webp.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\_webp.cp36-win_amd64.lib
    LINK : fatal error LNK1181: cannot open input file 'webp.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181
```

My current development environment is a conda virtual environment on Windows.

I've manually downloaded .zip from https://github.com/webmproject/libwebp
and moved include and lib files from it to the conda environment, but it doesn't solve my issue.

Thank you!

**Comment by anibali** [comment]
Unfortunately I don't really have the expertise to solve this problem. My development environment is Linux-based, and I'm not sure what the Windows story for Python+native libraries is.

To my eyes it looks like a path issue. You say that you moved the lib files, but have you double-checked that `webp.lib`, `webpdemux.lib`, and `webpmux.lib` are in one of the listed `/LIBPATH` locations, like `c:\users\junsik.whang\appdata\local\continuum\anaconda3\envs\pytorch\libs`?

**Comment by yadalik** [comment]
After installing:
`conda install -c conda-forge libwebp`
and then trying pip install webp it can't see .h files in location:
d:\Anaconda3\Library\include\webp\decode.h
d:\Anaconda3\Library\include\webp\encode.h
d:\Anaconda3\Library\include\webp\types.h
If I download source and put those 
`    #include "decode.h"
    #include "demux.h"
    #include "encode.h"
    #include "mux.h"
`

 files near to webp_build.py and change <> to "" - then  get 
`LINK : fatal error LNK1181: cannot open input file 'webp.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181`
I've get this error on Anaconda+python 3.6+win 10 x 64
Also, I can't find any webp.lib in anaconda directory (although it says that succesfully installed conda install -c conda-forge libwebp)

**Comment by yadalik** [comment]
Error on >pip install --upgrade webp:

`C:\Users\User>pip install --upgrade webp
Collecting webp
  Using cached https://files.pythonhosted.org/packages/bc/37/f269d27987fc049902d5505a0f404707aea003c1ce55f6fb3a476f29cd8d/webp-0.1.0a7.tar.gz
Requirement already satisfied, skipping upgrade: cffi>=1.0.0 in d:\anaconda3\lib\site-packages (from webp) (1.11.5)
Requirement already satisfied, skipping upgrade: Pillow>=4.0.0 in d:\anaconda3\lib\site-packages (from webp) (5.2.0)
Requirement already satisfied, skipping upgrade: numpy>=1.0.0 in d:\anaconda3\lib\site-packages (from webp) (1.15.1)
Requirement already satisfied, skipping upgrade: pycparser in d:\anaconda3\lib\site-packages (from cffi>=1.0.0->webp) (2.18)
Building wheels for collected packages: webp
  Running setup.py bdist_wheel for webp ... error
  Complete output from command d:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p3llno9y\\webp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\User\AppData\Local\Temp\pip-wheel-8fp1vod3 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\webp
  copying webp\webp_build.py -> build\lib.win-amd64-3.6\webp
  copying webp\__init__.py -> build\lib.win-amd64-3.6\webp
  running build_ext
  generating cffi module 'build\\temp.win-amd64-3.6\\Release\\_webp.c'
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  building '_webp' extension
  creating build\temp.win-amd64-3.6\Release\build
  creating build\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\anaconda3\include -Id:\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcbuild\temp.win-amd64-3.6\Release\_webp.c /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\_webp.obj
  _webp.c
  build\temp.win-amd64-3.6\Release\_webp.c(493): fatal error C1083: Cannot open include file: 'webp/decode.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for webp
  Running setup.py clean for webp
Failed to build webp
Installing collected packages: webp
  Running setup.py install for webp ... error
    Complete output from command d:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p3llno9y\\webp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\User\AppData\Local\Temp\pip-record-3qfq74eu\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\webp
    copying webp\webp_build.py -> build\lib.win-amd64-3.6\webp
    copying webp\__init__.py -> build\lib.win-amd64-3.6\webp
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.6\\Release\\_webp.c'
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    building '_webp' extension
    creating build\temp.win-amd64-3.6\Release\build
    creating build\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\anaconda3\include -Id:\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcbuild\temp.win-amd64-3.6\Release\_webp.c /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\_webp.obj
    _webp.c
    build\temp.win-amd64-3.6\Release\_webp.c(493): fatal error C1083: Cannot open include file: 'webp/decode.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "d:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p3llno9y\\webp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\User\AppData\Local\Temp\pip-record-3qfq74eu\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-install-p3llno9y\webp\`

**Comment by anibali** [comment]
Once again, I am not in a position to fix library path issues on Windows. I recommend trying to download and build libwebp 0.6.0 (https://github.com/webmproject/libwebp/releases/tag/v0.6.0), then making sure that the `.lib` and `.h` files are placed where Python can find them.

**Comment by anibali** [comment]
Actually, you might be able to just download http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-0.6.0-windows-x64.zip, it seems to have `libwebp.lib` prebuilt.

**Comment by anibali** [comment]
I installed Windows 10 in a VM and got everything working. Here's what you need to do.

1. Download and extract the source release of libwebp from  https://github.com/webmproject/libwebp/releases/tag/v0.6.0
2. Copy the entire `src\webp` directory into your conda include directory. For me it was `C:\Users\Aiden\Miniconda3\include`. So at this stage I had header files at `C:\Users\Aiden\Miniconda3\include\webp\*.h`
3. Open up the "x64 Native Tools Command Prompt" and change to the source release directory for libwebp
4. Compile the libwebp libraries with `nmake /f Makefile.vc CFG=release-static RTLIBCFG=static OBJDIR=output all`
5. You should see `libwebp.lib`, `libwebpdemux.lib`, and `libwebpmux.lib` in `output/release-static/x64`. Copy these files into your conda libs directory. For me it was `C:\Users\Aiden\Miniconda3\libs`
6. Rename the .lib files from `lib*.lib` to simply `*.lib`. For example, `libwebp.lib` becomes `webp.lib`. So at this stage I had `C:\Users\Aiden\Miniconda3\libs\{webp.lib,webpdemux.lib,webpmux.lib}`
7. You should now be able to build pywebp. To test this, run `python setup.py test`

**Comment by anibali** [comment]
I've changed the setup so that libwebp is automatically installed using Conan. This should make installation a lot easier in the future since it is no longer necessary to install libwebp separately. I've tested the new setup on Windows 10 and Ubuntu 16.04.

**Comment by topherbuckley** [comment]
> I've changed the setup so that libwebp is automatically installed using Conan. This should make installation a lot easier in the future since it is no longer necessary to install libwebp separately. I've tested the new setup on Windows 10 and Ubuntu 16.04.

Looks like this is no longer working (at least on Unbuntu 20.04). I can open a seperate issue if needed, just thought this looked possibly related.

Trying `<pathToPython> -m pip install webp` results in this:

```
ERROR: Command errored out with exit status 1:
     command: /home/christopher/git/smartphone-robot/util/pycharm/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4tg8nvo2/webp_db3897204a9245c595202926adcf4440/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4tg8nvo2/webp_db3897204a9245c595202926adcf4440/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3o8k9auv
         cwd: /tmp/pip-install-4tg8nvo2/webp_db3897204a9245c595202926adcf4440/
    Complete output (45 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /home/christopher/git/smartphone-robot/util/pycharm/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-tez_k1dq/conan_b1ba100c739a4fcd938d3c2a5339ad31/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-tez_k1dq/conan_b1ba100c739a4fcd938d3c2a5339ad31/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e73_195l
           cwd: /tmp/pip-wheel-tez_k1dq/conan_b1ba100c739a4fcd938d3c2a5339ad31/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for conan
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/christopher/git/smartphone-robot/util/pycharm/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmprnmegvs6', '--quiet', 'conan>=1.8.0']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4tg8nvo2/webp_db3897204a9245c595202926adcf4440/setup.py", line 6, in <module>
        setup(
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/setuptools/dist.py", line 686, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/christopher/git/smartphone-robot/util/pycharm/venv/lib/python3.8/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/christopher/git/smartphone-robot/util/pycharm/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmprnmegvs6', '--quiet', 'conan>=1.8.0']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/62/df/1efb36189ee596f6d3773c8c1b051ada90d244a601b0e4de00181e8fa6f9/webp-0.1.0.tar.gz#sha256=9f15bf22999789b05f12dd02e0970d44adf506e086ea9558e6c5abc4c5585126 (from https://pypi.org/simple/webp/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement webp (from versions: 0.1.0a4, 0.1.0a5, 0.1.0a6, 0.1.0a7, 0.1.0a9, 0.1.0a10, 0.1.0a11, 0.1.0a12, 0.1.0a13, 0.1.0a14, 0.1.0a15, 0.1.0a16, 0.1.0)
ERROR: No matching distribution found for webp
```

**Comment by anibali** [comment]
@topherbuckley I just tried on Ubuntu 20.04 and it installed without issue. One thing that I can think of based on your error output is that you might be missing wheel. Try running `pip install wheel` before installing webp.

**Comment by topherbuckley** [comment]
> @topherbuckley I just tried on Ubuntu 20.04 and it installed without issue. One thing that I can think of based on your error output is that you might be missing wheel. Try running `pip install wheel` before installing webp.

Yep! That did it. I was unaware that `wheel` was a package. I thought that error was referring to a missing wheel for webp in pip. Thanks for the fast response and I see you already set up an issue to add it to the setup so others don't run into this in the future.
