### ISSUE TITLE
Grayscale support

### ISSUE THREAD

**Issue by somebelly** [anibali/pywebp#22]
Hi,

Would you like to add the grayscale support? I'm not sure whether webp works with grayscale images, but using your python wrapper, I can only get "unsupported image mode: L" and have to convert the image to RGB first.

The problem is, generally, I use webp to reduce the file size, but if I convert a grayscale image to RGB and then to webp, sometimes, the file size could even increase (I got a png at 2mb but after this conversion, I got a webp at 4mb ...).

Thanks in advance.

**Comment by anibali** [comment]
WebP always stores the image in colour, see https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#webp_image. Perhaps another image file type would be more suitable.

**Comment by somebelly** [comment]
May I ask you if you have some recommendations for the grayscale format? (If png is not the best here)

**Comment by anibali** [comment]
I have no specific recommendation, but if you go to https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types and Ctrl+F "greyscale" you can shortlist a few formats and test them out for your needs. AVIF, JPG, and PNG are probably the most likely candidates depending on the nature of your images.

**Comment by somebelly** [comment]
Ok, thanks.
BTW as for this python wrapper maybe you can consider converting the L mode images to RBG as the default behavior rather than throwing out an error message.

**Comment by anibali** [comment]
I'm in two minds about this. On one hand, it is convenient for many users for the bindings to auto-convert from different PIL image modes. On the other hand, unlike https://github.com/anibali/pywebp/issues/17, it may actually be useful to throw an error message for greyscale images so that people such as yourself are prompted to consider whether WebP is actually a good choice.
