### ISSUE TITLE
urllib3 version conflict during package install

### ISSUE THREAD

**Issue by FeraruSilviuMarian** [anibali/pywebp#27]
I'll post a snippet of the error, basically I tried every other way, I tried downgrading urllib3 to 1.21.1 and 1.26 to no avail, I tried downloading the package from here and installing it from cmd with python setup.py install, I tried everything and I asked people in the python discord server, nothing seems to work, I'm using windows 10
Also, one of the people who tried to help me on the python server tried to install the module and got the same error

  File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
setuptools.sandbox.UnpickleableException: ContextualVersionConflict(urllib3 1.26.6 (c:\users\silve\appdata\local\temp\easy_install-lwmckpl5\webp-0.1.1\.eggs\urllib3-1.26.6-py3.8.egg), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})

**Comment by anibali** [comment]
I believe that this version conflict is arising from `conan` and not pywebp itself, since pywebp does not depend on urllib3 directly. To get a better understanding of what's going on I will need to know the current versions of packages that you have installed. Could you please post the output of `pip list`?

In the meantime, here are two things you can try that might solve your problem (remove urllib3 first):

1. Update `requests` to v2.26.0 (`pip install requests==2.26.0`) and try to install pywebp again.
2. If you still can't install pywebp, try installing an older version of Conan manually first: `pip install conan==1.36.0`. If you can't install Conan, then you won't be able to install pywebp.

**Comment by FeraruSilviuMarian** [comment]
`Package                         Version
------------------------------- -----------
aiohttp                         3.6.2
astroid                         2.4.0
async-timeout                   3.0.1
attrs                           19.3.0
beautifulsoup4                  4.9.3
bs4                             0.0.1
cachetools                      4.2.2
certifi                         2020.4.5.1
cffi                            1.14.6
chardet                         3.0.4
click                           7.1.2
cloudmersive-convert-api-client 3.2.1
colorama                        0.4.3
convertapi                      1.4.0
cs50                            5.0.3
dblpy                           0.3.4
decorator                       4.4.2
discord                         1.0.1
discord.py                      1.6.0
Flask                           1.1.2
futures                         3.1.1
giphypop                        0.3
google-api-core                 1.28.0
google-api-python-client        2.5.0
google-auth                     1.30.0
google-auth-httplib2            0.1.0
googleapis-common-protos        1.53.0
googletrans                     3.1.0a0
goslate                         1.5.1
h11                             0.9.0
h2                              3.2.0
haishoku                        1.1.8
hpack                           3.0.0
hstspreload                     2020.6.23
httpcore                        0.9.1
httplib2                        0.19.1
httpx                           0.13.3
hyperframe                      5.2.0
idna                            2.9
imageio                         2.9.0
imageio-ffmpeg                  0.4.5
install                         1.3.4
isort                           4.3.21
itsdangerous                    1.1.0
Jinja2                          2.11.2
keyboard                        0.13.5
lazy-object-proxy               1.4.3
MarkupSafe                      1.1.1
mccabe                          0.6.1
moviepy                         1.0.3
mpmath                          1.1.0
multidict                       4.7.5
newsapi-python                  0.2.6
npm                             0.1.1
numpy                           1.21.2
optional-django                 0.1.0
packaging                       20.9
Pillow                          8.3.2
pip                             21.2.4
proglog                         0.1.9
protobuf                        3.17.0
psutil                          5.8.0
pyasn1                          0.4.8
pyasn1-modules                  0.2.8
pycparser                       2.20
PyDictionary                    2.0.1
pygifsicle                      1.0.4
pylint                          2.5.0
pyparsing                       2.4.7
python-dateutil                 2.8.2
pytz                            2021.1
ratelimiter                     1.2.0.post0
regexp                          0.1
requests                        2.23.0
rfc3986                         1.4.0
rsa                             4.7.2
selenium                        3.141.0
setuptools                      41.2.0
six                             1.14.0
sniffio                         1.1.0
soupsieve                       2.2.1
SQLAlchemy                      1.3.16
sqlparse                        0.3.1
sympy                           1.5.1
termcolor                       1.1.0
toml                            0.10.0
tqdm                            4.62.2
urbandict                       0.6.1
uritemplate                     3.0.1
urllib3                         1.25.11
uuid                            1.30
Wand                            0.6.7
webptools                       0.0.6
websockets                      8.1
Werkzeug                        1.0.1
wheel                           0.37.0
wrapt                           1.12.1
yarl                            1.4.2`

**Comment by FeraruSilviuMarian** [comment]
C:\Users\silve>pip install pywebp
Collecting pywebp
  Downloading pywebp-0.0.1.tar.gz (1.3 kB)
ERROR: Could not find a version that satisfies the requirement request (from pywebp) (from versions: none)
ERROR: No matching distribution found for requestI've updated requests to the version specified, now I get a different error, I will try the rest of the steps, but for now this is the error:

**Comment by anibali** [comment]
You've encountered another issue which is described here: https://github.com/anibali/pywebp/issues/28

I've released v0.1.3 of webp which should fix this issue. Please try `pip install webp` again.

**Comment by FeraruSilviuMarian** [comment]
I've done pip cache flush then pip install webp and got this error

`
pip install webp
Collecting webp
  Downloading webp-0.1.2.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\silve\appdata\local\programs\python\python38-32\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\silve\\AppData\\Local\\Temp\\pip-install-9gbycj0_\\webp_78d78fa0ee9e4f5ea85e33c75c7c4c89\\setup.py'"'"'; __file__='"'"'C:\\Users\\silve\\AppData\\Local\\Temp\\pip-install-9gbycj0_\\webp_78d78fa0ee9e4f5ea85e33c75c7c4c89\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\silve\AppData\Local\Temp\pip-pip-egg-info-5w3tbtit'
         cwd: C:\Users\silve\AppData\Local\Temp\pip-install-9gbycj0_\webp_78d78fa0ee9e4f5ea85e33c75c7c4c89\
    Complete output (71 lines):
    Configuration:
    [settings]
    arch=x86_64
    arch_build=x86_64
    build_type=Release
    os=Windows
    os_build=Windows
    [options]
    [build_requires]
    [env]

    Traceback (most recent call last):
      File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\conans\client\graph\graph_builder.py", line 326, in _config_node
        run_configure_method(conanfile, down_options, down_ref, ref)

... (very long red text)


.py", line 359, in _resolve_recipe
        result = self._proxy.get_recipe(requirement.ref, check_updates, update,
      File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\conans\client\graph\proxy.py", line 33, in get_recipe
        result = self._get_recipe(layout, ref, check_updates, update, remotes, recorder)
      File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\conans\client\graph\proxy.py", line 49, in _get_recipe
        remote, new_ref = self._download_recipe(layout, ref, output, remotes, remotes.selected,
      File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\conans\client\graph\proxy.py", line 163, in _download_recipe
        raise NotFoundException(msg)
    conans.errors.NotFoundException: Unable to find 'libwebp/1.0.3@bincrafters/stable' in remotes
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/62/df/1efb36189ee596f6d3773c8c1b051ada90d244a601b0e4de00181e8fa6f9/webp-0.1.0.tar.gz#sha256=9f15bf22999789b05f12dd02e0970d44adf506e086ea9558e6c5abc4c5585126 (from https://pypi.org/simple/webp/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement webp (from versions: 0.1.0a4, 0.1.0a5, 0.1.0a6, 0.1.0a7, 0.1.0a9, 0.1.0a10, 0.1.0a11, 0.1.0a12, 0.1.0a13, 0.1.0a14, 0.1.0a15, 0.1.0a16, 0.1.0, 0.1.1, 0.1.2)
ERROR: No matching distribution found for webp`

**Comment by anibali** [comment]
I believe that the real error message is the one that you posted in https://github.com/anibali/pywebp/issues/28#issuecomment-916964174:

> Traceback (most recent call last):
  File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\conans\client\graph\graph_builder.py", line 326, in _config_node
    run_configure_method(conanfile, down_options, down_ref, ref)
  File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\conans\client\conanfile\configure.py", line 29, in run_configure_method
    conanfile.settings.validate()  # All has to be ok!
  File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\conans\model\settings.py", line 244, in validate
    child.validate()
  File "c:\users\silve\appdata\local\programs\python\python38-32\lib\site-packages\conans\model\settings.py", line 189, in validate
    raise undefined_value(self._name)
conans.errors.ConanException: 'settings.compiler' value not defined

This tells me that you don't have a compiler configured properly for Conan. See https://github.com/anibali/pywebp/issues/20 for how to deal with this.

**Comment by anibali** [comment]
I'm closing this issue since the original problem (urllib3 version conflict) has been resolved. I have opened a new issue regarding the Windows build error here: https://github.com/anibali/pywebp/issues/30. Please keep the discussion there and refrain from resurrecting old, resolved issues.
