### ISSUE TITLE
[Feature Request] Streamlining WebP Window's Installation

### ISSUE THREAD

**Issue by camUrban** [anibali/pywebp#33]
Hello! I think this package is excellent, and I am using it as a dependency for my package, [Ptera Software](https://github.com/camUrban/PteraSoftware). However, I noticed that some of my package's users encountered an issue when installing WebP. This seems to be the same issue as described in #20.

The workaround described in #20 is valid, and I've elaborated on it [here](https://github.com/camUrban/PteraSoftware/issues/15)). However, automating this process during WebP's installation would be very valuable.

I am still new to PyPI package management, so I don't know if this feature is possible. Therefore, I am posting this issue to start a discussion on if/how this could be implemented.

**Comment by anibali** [comment]
I have created a new release (v0.1.4) which includes binary wheels for Windows. This should make installation a lot smoother for the average Windows user since webp and my Python bindings will already be compiled and ready to go (no need for Conan). Please let me know whether this works for you.
