### ISSUE TITLE
Provide arm64 macOS wheel

### ISSUE THREAD

**Issue by laggykiller** [anibali/pywebp#44]
Hello, I saw that in `build_and_test.yml`, `universal2` wheel is being built and test. However, I only see `x86_64` wheels but I don't see `universal2` wheels provided in https://pypi.org/project/webp/#files

Uploading a pre-built universal2 wheel to pypi can allow users with arm64 macOS to install without requiring cmake and compiling on their end, hence avoid https://github.com/anibali/pywebp/issues/40

btw can you also update cibuildwheel to v2.15.0 to build wheels for python 3.12? Thank you.

**Comment by anibali** [comment]
For whatever reason, the universal2 wheels were note being built despite those settings. I will need to investigate further.

**Comment by anibali** [comment]
Python 3.12 support is a separate issue. It is not straightforward because of an issue with Conan 1.*, see here: https://github.com/conan-io/conan/pull/12149. To support Python 3.12, I would need to upgrade to Conan 2.

**Comment by laggykiller** [comment]
Thank you for your hardwork!

**Comment by laggykiller** [comment]
@anibali I have just tested macOS arm64 wheel, unfortunately it is not working...

The following error occurs after `import webp`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_webp.abi3.so, 0x0002): symbol not found in flat namespace '_WebPAnimDecoderDelete'
```

**Comment by anibali** [comment]
It is really difficult for me to work on this because I do not have access to an Apple Silicon machine (the wheels are cross-compiled). I'm currently thinking that the issue might be the same as this: https://github.com/Unidata/netcdf4-python/issues/1148#issuecomment-1017645753 (that is, the bindings are cross-compiled but the underlying webp library is not).

**Comment by laggykiller** [comment]
I forked your repo: https://github.com/laggykiller/pywebp/tree/c0e4ee851498658725bc463218ce742baca690ee

The most obvious reason that I could find is conan might not had cross-compiled libwebp, so I had made changes to `webp_build/builder.py`.

Also, I switched the `CIBW_BUILD_FRONTEND` to `build` to get more log for easy debugging

From here I can see that conan was cross-compiling libwebp: https://github.com/laggykiller/pywebp/actions/runs/6093108730/job/16532248458#step:4:894

From here I can see that gcc was linking the static libraries: https://github.com/laggykiller/pywebp/actions/runs/6093108730/job/16532248458#step:4:2751

Unfortunately, the same problem still occurs

**Comment by anibali** [comment]
Thanks for helping out with investigating this, you are trying exactly the right things and I'm keen to hear more about your findings. I do intend on upgrading to Conan 2 eventually since the Python 3.12 is just around the corner, but it's a bit more work than what I have time for right now

**Comment by laggykiller** [comment]
Turns out I have to:
- Specify `compiler.version=11.0` to conan settings (libwebp was linked, but since the default `compiler.version` set in `.conan/profiles/default` is `14.0`, there was mismatch of compiler version between libwebp and cffi binding)
- Add `extra_compiler_args` to cffi

While I am at it, I also added wheel building for all architectures supported by cibuildwheel (Windows x86, arm64; Linux i686, aarch64, ppc64le, s390x, musllinux). One side effect is GitHub action would take longer time, and I have to remove auto-download CMake by conan as only x64 and arm64 versions of CMake prebuilt binaries are provided, and I cannot instruct conan to compile CMake instead of trying to download incompatible version of CMake prebuilt binary. I don't think this would be a big problem though, as now we can provide prebuilt wheels to most of the users, and I think those who are using some exotic architectures should go download CMake themselves.

I have submited a pull request for building all architectures supported by cibuildwheel, please review. If you don't want to build all architectures, I can submit another pull request that only adds proper wheel building for macOS arm64.

**Comment by anibali** [comment]
Thanks for your great work! I will create another release soon with fixed macOS arm64 binaries
