### ISSUE TITLE
Security Address

### ISSUE THREAD

**Issue by SCH227** [anibali/pywebp#54]
Hello!

I may have found a security issue in latest version of Pywebp. Following responsible disclosure, is there an email or other private channel where I could share the details?
Thank you

**Comment by anibali** [comment]
You can find my email in the pyproject.toml file: https://github.com/anibali/pywebp/blob/master/pyproject.toml

**Comment by SCH227** [comment]
Emailed.
I recommend [adding a SECURITY.md](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) file in your repo so reporters have clear instructions on how to handle disclosures.
Thank you for your awesome project!

**Comment by anibali** [comment]
Thank you, received.

**Comment by anibali** [comment]
Addressed in pywebp 0.3.0. See the following security advisory for more details about the vulnerability: https://github.com/anibali/pywebp/security/advisories/GHSA-f9pm-4g9p-6vm3
