### ISSUE TITLE
GitHub arm64 macOS runner is now available, may enable test for it

### ISSUE THREAD

**Issue by laggykiller** [anibali/pywebp#58]
Source: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

You may want to build macOS arm64 wheel on arm64 CI runner so you can run test for both x86_64 and arm64 part of the wheel: https://github.com/anibali/pywebp/blob/5d6a916ccc07d94ca8df5eb1cfd62062c8dfea69/.github/workflows/build_and_test.yml#L146

**Comment by laggykiller** [comment]
I am trying to build pywebp with macos-14. During cibuildwheel test for the built universal2 wheel, it errored out as venv for testing x86_64 is reused for testing arm64, which contained x86_64 version of Pillow and cause error: https://github.com/laggykiller/pywebp/actions/runs/8074750021/job/22060570579#step:5:2147 . This is also discussed in https://github.com/pypa/cibuildwheel/issues/1746#issuecomment-1920164503 and fixed in https://github.com/pypa/cibuildwheel/pull/1750 .

I can confirm that pywebp builds without error with cibuildwheel that contain that fix (https://github.com/laggykiller/pywebp/actions/runs/8074902563/job/22060951096), however cibuildwheel has not released a new version that contain that fix. I will submit a PR once cibuildwheel release a new version.

btw From working on my personal project that also use conan, conan profile is not regenerated if it already exist and `-f` flag not present. Though it probably won't affect this project (This project does not use the cmake profile generated by conan), rebuilding without updated conan profile may cause much headache (See https://github.com/tttapa/py-build-cmake/issues/24). While we are at it, I will also add `-f` flag to `conan profile detect` in the PR.

**Comment by anibali** [comment]
That all sounds good, thank you!
