### ISSUE TITLE
Building abi3 wheel only

### ISSUE THREAD

**Issue by laggykiller** [anibali/pywebp#59]
According to [cffi documentation](https://cffi.readthedocs.io/en/latest/cdef.html#ffibuilder-compile-etc-compiling-out-of-line-modules), code produced by cffi >= 1.8 conatins `#define Py_LIMITED_API`, which makes the wheel abi3 compatible. This means we can just produce one abi3 wheel on minimum supported python version, and that wheel should work on all subsequent python 3 versions.

This reduces number of wheels needed to be built and uploaded to pypi, as well as eliminating the need to rebuild when python releases new versions.

All that is required in this project is to create `setup.cfg` and add:

```
[bdist_wheel]
py_limited_api = cp35
```

In theory the wheel produced should run in python 3.2, but the python code uses enum, which is first introduced in python 3.4. I could not install python 3.4, but I managed to verify that the wheel could be installed in python 3.5 on Linux, and passes all tests with pytest.

Github action building abi3 wheels with artifact: https://github.com/laggykiller/pywebp/actions/runs/8115496397

I have also added an action that run abi3audit, ensuring that the wheels built are abi3 compatible.

If you are interested, I can submit a PR, along with the PR mentioned in https://github.com/anibali/pywebp/issues/58

**Comment by anibali** [comment]
That is a really awesome find, thank you for bringing it to my attention. It should make all of the builds much more manageable, and I can use it in other projects too.

I would absolutely appreciate a PR, with the following alterations:

1. Place the `py_limited_api` option in setup.py to avoid creating setup.cfg
2. Keep the minimum Python version at 3.8 (it is almost 5 years old at this point, and the most recent version that is not yet EOL)
3. Bump the minimum required CFFI to 1.12

**Comment by laggykiller** [comment]
> Place the py_limited_api option in setup.py to avoid creating setup.cfg

This took me so long to find, it was poorly documented: https://github.com/pypa/wheel/issues/583

I have moved the setting into setup.py

> Keep the minimum Python version at 3.8

I was thinking of marking the absolute minimum required python version, but sure

> Bump the minimum required CFFI to 1.12

Makes sense

---

If you don't mind marking cibuildwheel version (See #58) as a commit, I can open a PR immediately:

```
uses: pypa/cibuildwheel@edd67e0d266e14537bbf2619e8c6a379ecb038fc
```

Or else, I can wait for next release of cibuildwheel before PR

**Comment by anibali** [comment]
I'd rather wait until the next release of cibuildwheel. Thanks again for your contributions!
