### ISSUE TITLE
TypeError: new() missing 1 required positional argument: 'enc_opts'

### ISSUE THREAD

**Issue by martmists** [anibali/pywebp#7]
I'm copying pretty much the exact code from the README:

```python
...
        enc = WebPAnimEncoder.new(*as_images[0].size)
        t = 0
        for img in as_images:
            pic = WebPPicture.from_pil(img)
            enc.encode_frame(pic, t)
            t += duration

        data = enc.assemble(t)
```

But this error appears:
```python
...
    enc = WebPAnimEncoder.new(*as_images[0].size)
TypeError: new() missing 1 required positional argument: 'enc_opts'
```

**Comment by anibali** [comment]
A quick solution for now is to do the following:

```
enc_opts = webp.WebPAnimEncoderOptions.new()
enc = webp.WebPAnimEncoder.new(*as_images[0].size, enc_opts)
```

I will fix the code so that it uses default `enc_opts` when none are specified, as I originally intended. Thanks for mentioning this.

**Comment by anibali** [comment]
Fixed in https://github.com/anibali/pywebp/commit/30bb92ed5e7d7878db33ebdbde350d5a8e639b40, please try release version 0.1.0a12.
